### ISSUE TITLE
Hows your setup with Cloudflare?

### ISSUE THREAD

**Issue by simplenotezy** [tarunmangukiya/nuxt-cloudflare-workers#1]
I'm developing a static nuxt site as well; I'm curious how your setup looks with Cloudflare Workers -- care to share some info? :)

**Comment by simplenotezy** [comment]
Nevermind, just found: https://morioh.com/p/952bc4e3b408 thanks a lot

**Comment by tarunmangukiya** [comment]
Glad to hear that!
I've article over here too: https://scotch.io/tutorials/deploying-a-static-nuxtjs-site-to-cloudflare-workers
